# Generated by Django 3.0.1 on 2019-12-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicdata', '0002_genre_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeezerTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_number', models.IntegerField()),
                ('track_number', models.IntegerField()),
                ('dz_id', models.BigIntegerField()),
                ('readable', models.BooleanField()),
                ('title_short', models.CharField(max_length=1000)),
                ('title_version', models.CharField(max_length=1000)),
                ('unseen', models.BooleanField()),
                ('link', models.URLField(max_length=2000)),
                ('rank', models.BigIntegerField()),
                ('release_date', models.DateField()),
                ('explicit_content_lyrics', models.IntegerField()),
                ('explicit_content_cover', models.IntegerField()),
                ('preview', models.URLField(max_length=2000)),
                ('bpm', models.FloatField()),
                ('gain', models.FloatField()),
                ('alternative_id', models.BigIntegerField(blank=True, null=True)),
                ('available_markets', models.ManyToManyField(to='musicdata.Market')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicdata.Recording')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeezerMp3',
            fields=[
                ('deezertrack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deezerdata.DeezerTrack')),
                ('title', models.CharField(max_length=1000)),
                ('artist_name', models.CharField(max_length=500)),
                ('album_name', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
            bases=('deezerdata.deezertrack',),
        ),
        migrations.CreateModel(
            name='DeezerAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=30, null=True)),
                ('barcode_type', models.CharField(choices=[('upc', 'UPC'), ('none', 'No barcode'), ('undef', 'Undefined')], default='none', max_length=30)),
                ('release_date', models.DateField()),
                ('label_name', models.CharField(max_length=1000)),
                ('dz_id', models.BigIntegerField()),
                ('link', models.URLField(max_length=2000)),
                ('share', models.URLField(max_length=2000)),
                ('cover_small', models.URLField(blank=True, max_length=2000, null=True)),
                ('cover_medium', models.URLField(blank=True, max_length=2000, null=True)),
                ('cover_big', models.URLField(blank=True, max_length=2000, null=True)),
                ('cover_xl', models.URLField(blank=True, max_length=2000, null=True)),
                ('nb_tracks', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('nb_fans', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('available', models.BooleanField()),
                ('alternative_id', models.BigIntegerField(blank=True, null=True)),
                ('tracklist_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('explicit_content_lyrics', models.IntegerField()),
                ('explicit_content_cover', models.IntegerField()),
                ('release_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicdata.ReleaseGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
