# Generated by Django 3.0.1 on 2019-12-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deezerdata", "0004_auto_20191222_2003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deezeralbum",
            name="available",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="barcode",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="cover_big",
            field=models.URLField(default="", max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="cover_medium",
            field=models.URLField(default="", max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="cover_small",
            field=models.URLField(default="", max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="cover_xl",
            field=models.URLField(default="", max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="explicit_content_cover",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="explicit_content_lyrics",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="explicit_lyrics",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="nb_fans",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="nb_tracks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezeralbum",
            name="tracklist_url",
            field=models.URLField(default="", max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deezertrack",
            name="bpm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezertrack",
            name="disc_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezertrack",
            name="explicit_content_cover",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezertrack",
            name="explicit_content_lyrics",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezertrack",
            name="explicit_lyrics",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezertrack",
            name="gain",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezertrack",
            name="rank",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezertrack",
            name="readable",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezertrack",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezertrack",
            name="track_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deezertrack",
            name="unseen",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
