# Generated by Django 3.0.1 on 2019-12-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0007_auto_20191225_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deezertrack',
            name='explicit_content_cover',
        ),
        migrations.RemoveField(
            model_name='deezertrack',
            name='explicit_content_lyrics',
        ),
        migrations.RemoveField(
            model_name='deezertrack',
            name='explicit_lyrics',
        ),
    ]
