# Generated by Django 3.0.1 on 2019-12-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deezerdata", "0008_auto_20191226_2034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deezeralbum",
            name="version",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="deezertrack",
            name="version",
            field=models.IntegerField(default=3),
        ),
    ]
