# Generated by Django 3.0.1 on 2019-12-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0011_auto_20191226_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deezertrack',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
