# Generated by Django 3.0.1 on 2019-12-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0012_auto_20191226_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deezertrack',
            name='unseen',
        ),
        migrations.AlterField(
            model_name='deezeralbum',
            name='version',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='deezertrack',
            name='version',
            field=models.IntegerField(default=6),
        ),
    ]
