# Generated by Django 3.0.1 on 2019-12-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0014_deezertrack_title_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deezeralbum',
            name='version',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='deezertrack',
            name='version',
            field=models.IntegerField(default=7),
        ),
    ]
