# Generated by Django 3.0 on 2020-03-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0019_deezeraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deezeraccount',
            name='version',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='deezeralbum',
            name='version',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='deezertrack',
            name='version',
            field=models.IntegerField(default=10),
        ),
    ]
