# Generated by Django 3.0 on 2020-04-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdata', '0021_auto_20200408_1746'),
        ('platform_apis', '0003_platformaccount'),
        ('deezerdata', '0020_auto_20200327_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deezeraccount',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='deezeraccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='deezeraccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='deezeraccount',
            name='last_history_request',
        ),
        migrations.RemoveField(
            model_name='deezeraccount',
            name='market',
        ),
        migrations.RemoveField(
            model_name='deezeraccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deezeraccount',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='deezeraccount',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='deezeraccount',
            name='version',
        ),
        migrations.RemoveField(
            model_name='deezertrack',
            name='available_markets',
        ),
        migrations.RemoveField(
            model_name='deezertrack',
            name='disc_number',
        ),
        migrations.RemoveField(
            model_name='deezertrack',
            name='id',
        ),
        migrations.RemoveField(
            model_name='deezertrack',
            name='recording',
        ),
        migrations.RemoveField(
            model_name='deezertrack',
            name='track_number',
        ),
        migrations.RemoveField(
            model_name='deezertrack',
            name='version',
        ),
        migrations.AddField(
            model_name='deezeraccount',
            name='platformaccount_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='platform_apis.PlatformAccount'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='deezermp3',
            name='deezertrack_ptr',
        ),
        migrations.AddField(
            model_name='deezertrack',
            name='track_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='musicdata.Track'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deezermp3',
            name='deezertrack_ptr',
            field=models.OneToOneField(auto_created=True, default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True, primary_key=True, serialize=False,
                to='deezerdata.DeezerTrack'),
            preserve_default=False,
        ),
    ]
