# Generated by Django 3.0 on 2020-04-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0021_auto_20200408_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deezeraccount',
            name='firstname',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='deezeraccount',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='deezeraccount',
            name='lastname',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
