# Generated by Django 3.0 on 2020-04-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0023_deezermp3_deezer_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deezeraccount',
            old_name='status',
            new_name='status_deezer',
        ),
    ]
