# Generated by Django 3.0 on 2020-04-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0024_auto_20200417_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deezeralbum',
            name='version',
            field=models.IntegerField(default=12),
        ),
    ]
