# Generated by Django 3.0 on 2020-04-18 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0025_auto_20200417_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='deezeralbum',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deezeralbum',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 14, 5, 31, 972542, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deezertrack',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deezertrack',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 14, 5, 44, 412652, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deezeralbum',
            name='version',
            field=models.IntegerField(default=13),
        ),
    ]
