# Generated by Django 3.0 on 2020-04-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0026_auto_20200418_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deezeralbum',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='deezeralbum',
            name='version',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='deezertrack',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
