# Generated by Django 3.0 on 2020-04-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0029_auto_20200423_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='deezertrack',
            name='title',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deezeralbum',
            name='version',
            field=models.IntegerField(default=33),
        ),
    ]
