# Generated by Django 3.0 on 2020-02-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200201_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeezerAccount',
        ),
    ]
