# Generated by Django 3.0 on 2020-04-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200327_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_history_request',
        ),
    ]
