# Generated by Django 3.0 on 2020-11-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200424_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='showcase_profile',
            field=models.BooleanField(default=False),
        ),
    ]
