# Generated by Django 2.2.6 on 2019-11-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('deezer_id', models.BigIntegerField(blank=True, null=True)),
                ('soptify_id', models.BigIntegerField(blank=True, null=True)),
                ('image_url_deezer_xl', models.URLField(
                    blank=True, max_length=2000, null=True)),
                ('image_url_deezer_large', models.URLField(
                    blank=True, max_length=2000, null=True)),
                ('image_url_deezer_medium', models.URLField(
                    blank=True, max_length=2000, null=True)),
                ('image_url_deezer_small', models.URLField(
                    blank=True, max_length=2000, null=True)),
                ('image_url_spotify_largest', models.URLField(
                    blank=True, max_length=2000, null=True)),
                ('image_url_spotify_medium', models.URLField(
                    blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('isrc', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=1000)),
                ('audio_features', models.TextField(blank=True, null=True)),
                ('audio_analysis', models.TextField(blank=True, null=True)),
                ('duration', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('album_type', models.CharField(choices=[('single', 'single'), ('album', 'album'), (
                    'EP', 'EP'), ('compilation', 'compilation'), ('undef', 'undefined')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseGroupContribution',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'main'), ('feat', 'featured'), (
                    'undef', 'undefined')], default='undef', max_length=20)),
                ('artist', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='musicdata.Artist')),
                ('release_group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='musicdata.ReleaseGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='releasegroup',
            name='contributors',
            field=models.ManyToManyField(
                through='musicdata.ReleaseGroupContribution', to='musicdata.Artist'),
        ),
        migrations.CreateModel(
            name='RecordingContribution',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'main'), ('feat', 'featured'), (
                    'undef', 'undefined')], default='undef', max_length=20)),
                ('artist', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='musicdata.Artist')),
                ('recording', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='musicdata.Recording')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='contributors',
            field=models.ManyToManyField(
                through='musicdata.RecordingContribution', to='musicdata.Artist'),
        ),
    ]
