# Generated by Django 3.0.1 on 2019-12-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicdata", "0010_auto_20191226_2201"),
    ]

    operations = [
        migrations.RemoveField(model_name="recording", name="audio_analysis",),
        migrations.RemoveField(model_name="recording", name="audio_features",),
        migrations.RemoveField(model_name="recording", name="duration",),
        migrations.RemoveField(model_name="recording",
                               name="explicit_content_cover",),
        migrations.RemoveField(model_name="recording",
                               name="explicit_content_lyrics",),
        migrations.RemoveField(model_name="recording",
                               name="explicit_lyrics",),
        migrations.RemoveField(model_name="recording", name="title_refine",),
        migrations.RemoveField(model_name="recording", name="title_short",),
        migrations.AlterField(
            model_name="artist", name="version", field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="genre", name="version", field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="market", name="version", field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="recording",
            name="version",
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="recordingcontribution",
            name="version",
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="releasegroup",
            name="version",
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="releasegroupcontribution",
            name="version",
            field=models.IntegerField(default=4),
        ),
    ]
