# Generated by Django 3.0.1 on 2019-12-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicdata", "0014_auto_20191226_2308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist", name="version", field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="genre", name="version", field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="market", name="version", field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="recording",
            name="version",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="recordingcontribution",
            name="version",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="releasegroup",
            name="version",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="releasegroupcontribution",
            name="version",
            field=models.IntegerField(default=8),
        ),
    ]
