# Generated by Django 3.0.1 on 2019-12-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdata', '0016_auto_20191226_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='english_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
