# Generated by Django 3.0.1 on 2020-01-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deezerdata", "0018_auto_20200101_2233"),
        ("musicdata", "0017_auto_20191227_0003"),
    ]

    operations = [
        migrations.DeleteModel(name="Market",),
    ]
