# Generated by Django 3.0 on 2020-03-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_apis', '0002_auto_20200327_1939'),
        ('musicdata', '0019_auto_20200327_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=10)),
                ('disc_number', models.IntegerField(blank=True, null=True)),
                ('track_number', models.IntegerField(blank=True, null=True)),
                ('available_markets', models.ManyToManyField(to='platform_apis.Market')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='musicdata.Recording')),
            ],
        ),
    ]
