# Generated by Django 3.0 on 2020-04-08 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdata', '0020_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='deezer_track',
        ),
    ]
