# Generated by Django 3.0 on 2020-04-08 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0021_auto_20200408_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='deezer_track',
            field=models.ForeignKey(blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+', to='deezerdata.DeezerTrack'),
        ),
    ]
