# Generated by Django 3.0 on 2020-04-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicdata', '0021_auto_20200408_1746'),
        ('musicdata', '0022_auto_20200408_1751'),
    ]

    operations = [
    ]
