# Generated by Django 3.0 on 2020-04-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicdata', '0023_merge_20200408_1804'),
        ('musicdata', '0018_auto_20200102_2201'),
    ]

    operations = [
    ]
