# Generated by Django 3.0 on 2020-04-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdata', '0025_track_track_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasegroup',
            name='genres',
            field=models.ManyToManyField(to='musicdata.Genre'),
        ),
    ]
