# Generated by Django 3.0 on 2020-04-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdata', '0027_auto_20200417_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='version',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='genre',
            name='version',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='recording',
            name='version',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='recordingcontribution',
            name='version',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='releasegroup',
            name='version',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='releasegroupcontribution',
            name='version',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='track',
            name='version',
            field=models.IntegerField(default=12),
        ),
    ]
