# Generated by Django 3.0 on 2020-04-18 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicdata', '0028_auto_20200417_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='deleted_deezer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='last_update_deezer',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 14, 5, 51, 983424, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='version',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='genre',
            name='version',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='recording',
            name='version',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='recordingcontribution',
            name='version',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='releasegroup',
            name='version',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='releasegroupcontribution',
            name='version',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='track',
            name='version',
            field=models.IntegerField(default=13),
        ),
    ]
