# Generated by Django 3.0 on 2020-04-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdata', '0029_auto_20200418_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='last_update_deezer',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='version',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='genre',
            name='version',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='recording',
            name='version',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='recordingcontribution',
            name='version',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='releasegroup',
            name='version',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='releasegroupcontribution',
            name='version',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='track',
            name='version',
            field=models.IntegerField(default=14),
        ),
    ]
