# Generated by Django 3.0 on 2020-04-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdata', '0030_auto_20200418_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='version',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='genre',
            name='version',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='recording',
            name='version',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='recordingcontribution',
            name='version',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='releasegroup',
            name='version',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='releasegroupcontribution',
            name='version',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='track',
            name='version',
            field=models.IntegerField(default=30),
        ),
    ]
