# Generated by Django 3.0 on 2020-03-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historyentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("listening", "Track listening"),
                    ("err_deezer", "Deezer error"),
                    ("ellipsis", "History Ellipsis (Deezer)"),
                ],
                default="listening",
                max_length=100,
            ),
        ),
    ]
