# Generated by Django 3.0 on 2020-04-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdata', '0020_track'),
        ('history', '0003_auto_20200327_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyentry',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='historyentry',
            name='track_type',
        ),
        migrations.AddField(
            model_name='historyentry',
            name='track',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='musicdata.Track'),
            preserve_default=False,
        ),
    ]
