# Generated by Django 3.0 on 2020-04-16 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdata', '0025_track_track_type'),
        ('history', '0004_auto_20200408_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyentry',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='musicdata.Track'),
        ),
    ]
