# Generated by Django 3.0 on 2020-04-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deezerdata', '0023_deezermp3_deezer_account'),
        ('history', '0006_auto_20200416_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyentry',
            name='deezer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deezerdata.DeezerAccount'),
        ),
    ]
