# Generated by Django 3.0 on 2020-04-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_historyentry_deezer_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyentry',
            name='version',
            field=models.IntegerField(default=11),
        ),
    ]
