# Generated by Django 3.0 on 2020-04-12 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RetrievalError',
            new_name='ExceptionLog',
        ),
    ]
