# Generated by Django 3.0 on 2020-04-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionlog',
            name='function_name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
