# Generated by Django 3.0 on 2020-03-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='version',
            field=models.IntegerField(default=10),
        ),
    ]
