# Generated by Django 3.0 on 2020-03-29 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200327_1939'),
        ('platform_apis', '0002_auto_20200327_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=10)),
                ('user_id', models.CharField(max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('last_history_request', models.DateTimeField(blank=True, default=datetime.datetime(1969, 12, 31, 23, 0, tzinfo=utc), null=True)),
                ('name', models.CharField(max_length=300)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='platform_apis.Market')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
